config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'
	root 'static_pages#home'
	get '/help', 		to: "static_pages#help"
	get '/about', 		to: "static_pages#about"

	# get '/signup', 	to: "users#new"
	# post '/signup', to: "users#create"
#	get 'users/:id',to: "users#show", as: "user"

	get '/signup', 		to: "users#new"
	post '/signup', 	to: "users#create"

	get '/login',		to: "sessions#new"
	post '/login',		to: "sessions#create"
	delete '/logout',	to: "sessions#destroy"

	resources :users, 		except: :new do
		member do 
		get :following, :followers
		end
	end	

	resources :microposts, 				only: [:create, :destroy]

	resources :relationships, 			only: [:create, :destroy]
	resources :account_activations, 	only: [:edit]


end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div>
		<div class="alert alert-danger">
		<h4>You have <%= pluralize(object.errors.count, "error") %> .</h4>
		</div>

		<div>
			<% object.errors.full_messages.each do |message| %>
				<ul>
					<li><%= message %></li>
				</ul>
			<% end %>	
		</div>
	</div>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for @micropost do |f| %>
	<%= render 'shared/error_messages', object: f.object %>

	<div class="form-group">							
		<% f.label :content %>
		<%= f.text_area :content, placeholder: "Compose new micropost...", class: 'form-control' %>
	</div>

	<%= f.submit "Post", class: 'btn btn-primary form-control' %>
 	<span class="picture"> 
		<%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
		</span>
<% end %>

<script type="text/javascript"> 
	$('#micropost_picture').bind('change', function() {
	var size_in_megabytes = this.files[0].size/1024/1024; if (size_in_megabytes > 5) {
	alert('Maximum file size is 5MB. Please choose a smaller file.');
		}
	});
</script>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>

<div class="stats">
	<%= link_to following_user_path(@user) do %> 
		<strong class="stat">
			<%= @user.following.count %>
		<strong>
		following
	<% end %>

	<%= link_to followers_user_path(@user) do %> 
		<strong class="stat">
			<%= @user.followers.count %>

			followers
		</strong>
	<% end %>
</div>

app/views/shared/_user_info.html.erb
<aside>
	<%= gravatar_for(current_user) %>
	<span><%= current_user.name %></span>
	<span><%= link_to "View my profile", user_path(current_user.id) %></span>
	<span><%= pluralize(current_user.microposts.count, "micropost") %></span>
</aside>