config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'
	root 'static_pages#home'
	get '/help', 		to: "static_pages#help"
	get '/about', 		to: "static_pages#about"

	# get '/signup', 	to: "users#new"
	# post '/signup', to: "users#create"
#	get 'users/:id',to: "users#show", as: "user"

	get '/signup', 		to: "users#new"
	post '/signup', 	to: "users#create"

	get '/login',		to: "sessions#new"
	post '/login',		to: "sessions#create"
	delete '/logout',	to: "sessions#destroy"

	resources :users, 		except: :new do
		member do 
		get :following, :followers
		end
	end	

	resources :microposts, 				only: [:create, :destroy]

	resources :relationships, 			only: [:create, :destroy]
	resources :account_activations, 	only: [:edit]


end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  default_scope -> {order(created_at: :desc)} # lamda
  mount_uploader :picture, PictureUploader  # carrier wave
  validates	:user_id, presence: true
  validates	:content, presence: true, length: { maximum: 140 }
  validate :picture_size

  private
  
	def picture_size
	 if picture.size > 5.megabytes # size = carrier wave provides us method
	    errors.add(:picture, "should be less than 5MB") 
   end
	end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController

	before_action :logged_in_user, only: [:create, :destroy]
	before_action :correct_user, only: [:destroy]


	def create
		@micropost = current_user.microposts.build(micropost_params) # new
		if @micropost.save
			flash[:success] = "Your new post is created." # success -> green, danger -> red bootstrap func
			redirect_to root_path
		else
			@feed_items = current_user.feed.paginate(page: params[:page])
			render 'static_pages/home' #root_path
		end
	end

	def destroy
		@micropost.destroy
		flash[:success] = "Micropost deleted."
		redirect_to request.referrer || root_path	
	end	


	private

	def micropost_params
		params.require(:micropost).permit(:content, :picture)
	end

	def correct_user
		@micropost = current_user.microposts.find_by(id: params[:id])
		redirect_to root_path if @micropost.nil?

		#micropost = Micropost.find(params[:id])
		# @micropost = Micropost.find(params[:id])
		# unless current_user == @micropost.user
		### unless current_user.id == @micropost.user_id
		# 	redirect_to root_path
		# end

		#redirect_to root_path unless current_user?(@micropost.user)

	end

end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_micropost.html.erb
<li id="micropost"-<%= micropost.id %>>
<!-- 	<%#= @user.name %> : <%= micropost.content %> -->
	<%= link_to gravatar_for(micropost.user, 50), micropost.user, class: 'gravatar' %>

	<span class="user">
<!-- 		<%#=link_to micropost.user.name, user_path(@user.id) %> -->
		<%= link_to micropost.user.name, micropost.user %>
	</span>

	<div>
		<span class="content">
			<%= micropost.content %>
 			<%= image_tag micropost.picture.url if micropost.picture? %>
		</span>
	</div>

	<span class="timestamp">
		Posted <%= time_ago_in_words(micropost.created_at) %>
	</span>

<!-- 	<#% if current_user == micropost.user %> -->
	<% if current_user?(micropost.user) %>
		<%= link_to "delete", micropost, method: :delete, data: { confirm: "Are you sure?"} %>
	<!-- 	<%#= link_to "delete", micropost_path(micropost.id) %> -->
	<% end %>
</li>