config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'
	root 'static_pages#home'
	get '/help', 		to: "static_pages#help"
	get '/about', 		to: "static_pages#about"

	# get '/signup', 	to: "users#new"
	# post '/signup', to: "users#create"
#	get 'users/:id',to: "users#show", as: "user"

	get '/signup', 		to: "users#new"
	post '/signup', 	to: "users#create"

	get '/login',		to: "sessions#new"
	post '/login',		to: "sessions#create"
	delete '/logout',	to: "sessions#destroy"

	resources :users, 		except: :new do
		member do 
		get :following, :followers
		end
	end	

	resources :microposts, 				only: [:create, :destroy]

	resources :relationships, 			only: [:create, :destroy]
	resources :account_activations, 	only: [:edit]


end

app/views/layouts/_header.html.erb
<header>
<nav class="navbar navbar-default navbar-inverse">
	<div class="container">
		<%= link_to "Awesomeblog", root_path, class: "navbar-brand" %>

		<ul class="nav navbar-nav navbar-right">
			<li><%= link_to "Home", root_path %></li>
			<li><%= link_to "Help", help_path %></li>
			<% if logged_in? %>
				<li><%= link_to "Users", users_path %></li>
				<li role ="button" class="dropdown">
					<a class="dropdown-toggle" data-toggle="dropdown"  aria-haspopup="true" aria-expanded="false">
						Account
						<span class="caret"></span>
					</a>
					<ul class="dropdown-menu">
						<li><%= link_to "Profile", current_user %></li>
						<li><%= link_to "Setting", edit_user_path(current_user) %></li>
						<li><%= link_to "Logout", logout_path, method: :delete %></li>
					</ul>					
				</li>
			<% else %>
				<li><%= link_to "About", about_path %></li>
				<li><%= link_to "Login", login_path %></li>
			<% end %>
		</ul>
	</div>

</nav>	
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>">
            <%= message %>
        </div>
      <% end %>
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>